require:
  - "rubocop-rspec"
  - "rubocop-capybara"
  - "anycable/rails/compatibility/rubocop"

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable

Lint:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  Enabled: true

AnyCable/InstanceVars:
  Enabled: true

AnyCable/StreamFrom:
  Enabled: true

AnyCable/PeriodicalTimers:
  Enabled: true
