require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100
  Exclude:
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"
