module TwilioAPI
  class StatusCallbackSerializer < TwilioAPISerializer
    # https://www.twilio.com/docs/voice/api/call-resource#statuscallback

    # | Parameter     | Description                                                                                                                 |
    # | ------------- | --------------------------------------------------------------------------------------------------------------------------- |
    # | CallSid       | A unique identifier for this call, generated by Twilio.                                                                     |
    # | AccountSid    | Your Twilio account ID.                                                                                                     |
    # | From          | The phone number or client identifier of the party that initiated the call.                                                 |
    # | To            | The phone number or client identifier of the called party.                                                                  |
    # | CallStatus    | A descriptive status for the call.                                                                                          |
    # | ApiVersion    | The version of the Twilio API used to handle this call.                                                                     |
    # | Direction     | A string describing the direction of the call                                                                               |
    # | ForwardedFrom | This parameter is only set when Twilio receives a forwarded call.                                                           |
    # | CallerName    | This parameter is set when the IncomingPhoneNumber that received the call has set its VoiceCallerIdLookup value to true     |
    # | ParentCallSid | A unique identifier for the call that created this leg. If this is the first leg of a call, this parameter is not included. |

    def attributes
      super.merge(
        "CallSid" => nil,
        "AccountSid" => nil,
        "From" => nil,
        "To" => nil,
        "CallStatus" => nil,
        "ApiVersion" => nil,
        "Direction" => nil,
        "CallDuration" => nil,
        "SipResponseCode" => nil,
        "CallbackSource" => nil,
        "Timestamp" => nil,
        "SequenceNumber" => nil
      )
    end

    def CallSid
      sid
    end

    def AccountSid
      account_sid
    end

    def From
      format_number(__getobj__.from)
    end

    def To
      format_number(__getobj__.to)
    end

    def CallStatus
      status
    end

    def ApiVersion
      ApplicationSerializer::API_VERSION
    end

    def Direction
      direction
    end

    def CallDuration
      duration
    end

    def SipResponseCode
      __getobj__.call_data_record.sip_term_status
    end

    def CallbackSource
      "call-progress-events"
    end

    def Timestamp
      Time.current.utc.rfc2822
    end

    def SequenceNumber
      "0"
    end

    private

    def format_number(number)
      Phony.plausible?(number) ? "+#{number}" : number
    end
  end
end
