development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production: &production
  adapter: redis
  url: <%= Rails.configuration.app_settings.fetch(:redis_url) %>
  channel_prefix: somleng_production

staging:
  <<: *production
  channel_prefix: somleng_staging
