development:
  adapter: postgresql

test:
  adapter: test

production: &production
  adapter: postgresql
  channel_prefix: somleng_production

staging:
  <<: *production
  channel_prefix: somleng_staging
