default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  reaping_frequency: 10

development: &development
  primary:
    <<: *default
    database: somleng_development
  primary_replica:
    <<: *default
    database: somleng_development
    replica: true

test:
  primary:
    <<: *default
    database: somleng_test
  primary_replica:
    <<: *default
    database: somleng_test
    replica: true

production: &production
  primary:
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
  primary_replica:
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
    host: <%= ENV.fetch("DATABASE_RO_HOST") { ENV["DATABASE_HOST"] } %>
    replica: true

staging:
  <<: *production
