shared:
  apple:
    # Token auth params
    # See https://developer.apple.com/documentation/usernotifications/establishing-a-token-based-connection-to-apns
    key_id: your_key_id
    encryption_key: your_apple_encryption_key

    team_id: your_apple_team_id
    # Your identifier found on https://developer.apple.com/account/resources/identifiers/list
    topic: your.bundle.identifier

    # Set this to the number of threads used to process notifications (default: 5).
    # When the pool size is too small a ConnectionPool::TimeoutError error will be raised.
    # connection_pool_size: 5

    # Change the request timeout (default: 30).
    # request_timeout: 60

    # Decide when to connect to APNs development server.
    # Please note that anything built directly from Xcode and loaded on your phone will have
    # the app generate DEVELOPMENT tokens, while everything else (TestFlight, Apple Store, ...)
    # will be considered as PRODUCTION environment.
    # connect_to_development_server:

  google:
    # Your Firebase project service account credentials
    # See https://firebase.google.com/docs/cloud-messaging/auth-server
    encryption_key: <%= Rails.configuration.app_settings.fetch(:firebase_service_account_json_file).to_json.dump %>

    # Firebase project_id
    project_id: <%= Rails.configuration.app_settings.fetch(:firebase_project_id) %>

    # Change the request timeout (default: 15).
    # request_timeout: 30
