ignored_endpoints:
  - OkComputer::OkComputerController#show
  - OkComputer::OkComputerController#index

production: &production
  authentication: <%= Rails.application.app_settings.skylight_authentication_token %>

staging: &staging
  <<: *production
