ignored_endpoints:
  - OkComputer::OkComputerController#show
  - OkComputer::OkComputerController#index

production: &production
  authentication: <%= Rails.configuration.app_settings.fetch(:skylight_authentication_token) %>

staging: &staging
  <<: *production
