default: &default
  internal_api_http_auth_user: "user"
  internal_api_http_auth_password: "secret"

production:
  <<: *default
  internal_api_http_auth_user: <%= ENV["INTERNAL_API_HTTP_AUTH_USER"] %>
  internal_api_http_auth_password: <%= ENV["INTERNAL_API_HTTP_AUTH_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default
