name: Cleanup Packages

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cleanup_packages:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Untagged 'somleng' Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'somleng'
          package-type: 'container'
          delete-only-untagged-versions: 'true'

      - name: Delete Untagged 'somleng-nginx' Packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'somleng-nginx'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
